Cleanroom support
intergrav/devins-badges pull request #84
Opened 2024-05-16 08:05 UTC by Oganesson897

created some badgets for new mc modloader platform cleanroom.

2024-05-22 09:08 UTC, PSGitHubUser1 commented
make it darker..
the background

2024-06-17 20:49 UTC, bleonard252 requested changes
Suggestion: darken the background to improve contrast and readability.

2024-06-19 09:34 UTC, PSGitHubUser1 commented
> Suggestion: darken the background to improve contrast and readability.

yes, thats what I wanted to say

2024-07-26 00:18 UTC, Oganesson897 commented
updated

2025-01-25 06:14 UTC, closed without merging